services:
  redis:
    image: bitnami/valkey:7.2
    container_name: chief_redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/valkey/data
    healthcheck:
      test: ["CMD-SHELL", "echo", "true"]
      interval: 5s
      timeout: 3s
      retries: 1
    environment:
      VALKEY_PASSWORD: "${PASSWORD}"
    networks:
      - chief_dev

  postgres:
    image: postgres:16-alpine
    container_name: chief_postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 3s
      retries: 5
    environment:
      POSTGRES_PASSWORD: "${PASSWORD}"
      POSTGRES_USER: "chief"
      POSTGRES_DB: "chief"
    networks:
      - chief_dev

  controller:
    image: chief
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: chief_controller
    restart: always
    ports:
      - 3000:3000
      - 4000:4000
    depends_on:
      - redis
      - postgres
    healthcheck:
      test: ["CMD", "echo", "1"]
      interval: 5s
      timeout: 3s
      retries: 1
    environment:
      APP_DOMAIN: "http://${DOMAIN}"
      DATABASE_URL: "postgres://chief:${PASSWORD}@chief_postgres:5432/chief"
      REDIS_URL: "redis://:${PASSWORD}@chief_redis:6379"
      REDIS_HOSTNAME: "chief_redis"
      REDIS_PORT: "6379"
      REDIS_PASSWORD: "${PASSWORD}"
      DOMAIN: "${DOMAIN}"
      NEXT_PUBLIC_CHIEF_VERSION: "dev"
    volumes:
      - ./apps/ui/src:/app/apps/ui/src
      - ./apps/controller/src:/app/apps/controller/src
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Caddyfile:/Caddyfile
      - caddy_sites:/sites
    networks:
      - chief_dev
  proxy:
    image: caddy:latest
    container_name: chief_proxy
    restart: always
    ports:
      - 80:80
      - 443:443
      - 2019:2019
    healthcheck:
      test: ["CMD", "echo", "1"]
      interval: 5s
      timeout: 3s
      retries: 1
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_sites:/sites
    networks:
      - chief_dev

networks:
  chief_dev:
    name: chief_dev
    # driver: overlay

volumes:
  redis_data:
  postgres_data:
  caddy_data:
  caddy_sites:
